# This file was generated by GoReleaser. DO NOT EDIT.
cask "sm-beta" do
  version "0.5.0-beta.2"

  on_macos do
    on_intel do
      sha256 "0311e08c3e664ad31c8446649b0c01b4a0da0a5dea753ac891cd8868ec52a603"
      url "https://github.com/dukechain2333/ai-sessions-manager/releases/download/v#{version}/sm_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6f89881401a5a84e400a89856fb0262bf7949f2a978ad9b4726b8679b6ce0b1c"
      url "https://github.com/dukechain2333/ai-sessions-manager/releases/download/v#{version}/sm_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "386d5f2d5dede5bf7f9988becddf12a5d923031a284078e41bb69e536f084f97"
      url "https://github.com/dukechain2333/ai-sessions-manager/releases/download/v#{version}/sm_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "77bca05f737ea7a951bf0e5566ea0708a54007dc7cda67c774c49fa6cb28823e"
      url "https://github.com/dukechain2333/ai-sessions-manager/releases/download/v#{version}/sm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sm-beta"
  desc "TUI to browse and resume Claude Code sessions (beta channel)"
  homepage "https://github.com/dukechain2333/ai-sessions-manager"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sm-beta"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sm"]
    end
  end

  # No zap stanza required

end
