# This file was generated by GoReleaser. DO NOT EDIT.
cask "sm-beta" do
  version "0.5.0-beta.3"

  on_macos do
    on_intel do
      sha256 "967effad2f357abe728caf3519579d78d200a7ac824babcb83a90f5386e59853"
      url "https://github.com/dukechain2333/ai-sessions-manager/releases/download/v#{version}/sm_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f5749e3d760996c0c70c355546cc948429f1cfdc1802428bf87dd2ca458de84b"
      url "https://github.com/dukechain2333/ai-sessions-manager/releases/download/v#{version}/sm_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5c9ae3a42c14f24227dcbd2fe8ebaf4b5703142a0b9f909cffb7d029b5b15b30"
      url "https://github.com/dukechain2333/ai-sessions-manager/releases/download/v#{version}/sm_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1bd3f939a0658c02d780672450b41e32314e22f36aabd19b52c028f55e0d6c3d"
      url "https://github.com/dukechain2333/ai-sessions-manager/releases/download/v#{version}/sm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sm-beta"
  desc "TUI to browse and resume Claude Code sessions (beta channel)"
  homepage "https://github.com/dukechain2333/ai-sessions-manager"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sm"]
    end
  end

  # No zap stanza required

end
