# This file was generated by GoReleaser. DO NOT EDIT.
cask "sm" do
  version "0.4.2"

  on_macos do
    on_intel do
      sha256 "b438a4cafb45e8be1ac3f30568af191bf488602316d604d20d5748d80c5021e3"
      url "https://github.com/dukechain2333/ai-sessions-manager/releases/download/v#{version}/sm_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cc43f8c6e734d2919405dfbcf1f58595ed453c60bdf093ee6a24a4ff4f51fbfb"
      url "https://github.com/dukechain2333/ai-sessions-manager/releases/download/v#{version}/sm_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6644dc5f1fbc324081d3563332e58d452f1da25b25749394e0a5f19a95ab56f8"
      url "https://github.com/dukechain2333/ai-sessions-manager/releases/download/v#{version}/sm_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "494f7a14ac8e2fed739e7f45f5ff3993a1ca846371a6690affafcc6eb06f0c14"
      url "https://github.com/dukechain2333/ai-sessions-manager/releases/download/v#{version}/sm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sm"
  desc "TUI to browse and resume Claude Code sessions across directories"
  homepage "https://github.com/dukechain2333/ai-sessions-manager"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sm"]
    end
  end

  # No zap stanza required

end
