# This file was generated by GoReleaser. DO NOT EDIT.
cask "sm" do
  version "0.6.3"

  on_macos do
    on_arm do
      sha256 "b7c96ac3d456549728d7fc92c8a27624fcb0af0a649129e3a28bcb69bb849d06"
      url "https://github.com/dukechain2333/ai-sessions-manager/releases/download/v#{version}/sm_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4cfb45598917f26d72944dbee8fbb1e023cbd2c4ceb389ac4d338a9d9b034927"
      url "https://github.com/dukechain2333/ai-sessions-manager/releases/download/v#{version}/sm_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7edf4edf1d783c7063bfa52f7f3ddee8735bc9abd56f7223b7e564e7435d7448"
      url "https://github.com/dukechain2333/ai-sessions-manager/releases/download/v#{version}/sm_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7217f1e979eb5f21d8d882a57a3148a79d4c575033d2bd01d8a0849dfeac69eb"
      url "https://github.com/dukechain2333/ai-sessions-manager/releases/download/v#{version}/sm_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sm"
  desc "TUI to browse and resume Claude Code sessions across directories"
  homepage "https://github.com/dukechain2333/ai-sessions-manager"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sm"]
    end
  end

  # No zap stanza required
end
