# This file was generated by GoReleaser. DO NOT EDIT.
cask "sm" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "6b3e0493eac7721792da2e73029310a82ab50387aacbe263013dbe8000a0428d"
      url "https://github.com/dukechain2333/ai-sessions-manager/releases/download/v#{version}/sm_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7bdf14d2b632e0d947d0c263b615631164a996ae6e1225dd755168cc9b4b4191"
      url "https://github.com/dukechain2333/ai-sessions-manager/releases/download/v#{version}/sm_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6af93492768d10ae0cc975a2b405c4def321e6f40a22210e94102ca5db0a2345"
      url "https://github.com/dukechain2333/ai-sessions-manager/releases/download/v#{version}/sm_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c84721f9f23a057c6ea13d2d2eaa3e9d564deff0efb0adc50508af44832869b2"
      url "https://github.com/dukechain2333/ai-sessions-manager/releases/download/v#{version}/sm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sm"
  desc "TUI to browse and resume Claude Code sessions across directories"
  homepage "https://github.com/dukechain2333/ai-sessions-manager"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sm"]
    end
  end

  # No zap stanza required

end
